export interface Country {
  code: string;
  name: string;
  dial: string;
  flag: string;
  tz: string[];
}

export const countries: Country[] = [
  { code: 'US', name: 'United States', dial: '+1', flag: '🇺🇸', tz: ['America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles', 'America/Anchorage', 'Pacific/Honolulu'] },
  { code: 'CA', name: 'Canada', dial: '+1', flag: '🇨🇦', tz: ['America/Toronto', 'America/Vancouver', 'America/Edmonton', 'America/Winnipeg', 'America/Halifax', 'America/St_Johns'] },
  { code: 'GB', name: 'United Kingdom', dial: '+44', flag: '🇬🇧', tz: ['Europe/London', 'Europe/Belfast'] },
  { code: 'AU', name: 'Australia', dial: '+61', flag: '🇦🇺', tz: ['Australia/Sydney', 'Australia/Melbourne', 'Australia/Perth', 'Australia/Brisbane', 'Australia/Adelaide', 'Australia/Darwin', 'Australia/Hobart'] },
  { code: 'PK', name: 'Pakistan', dial: '+92', flag: '🇵🇰', tz: ['Asia/Karachi'] },
  { code: 'IN', name: 'India', dial: '+91', flag: '🇮🇳', tz: ['Asia/Kolkata'] },
  { code: 'AE', name: 'UAE', dial: '+971', flag: '🇦🇪', tz: ['Asia/Dubai'] },
  { code: 'SA', name: 'Saudi Arabia', dial: '+966', flag: '🇸🇦', tz: ['Asia/Riyadh'] },
  { code: 'SG', name: 'Singapore', dial: '+65', flag: '🇸🇬', tz: ['Asia/Singapore'] },
  { code: 'MY', name: 'Malaysia', dial: '+60', flag: '🇲🇾', tz: ['Asia/Kuala_Lumpur'] },
  { code: 'PH', name: 'Philippines', dial: '+63', flag: '🇵🇭', tz: ['Asia/Manila'] },
  { code: 'BD', name: 'Bangladesh', dial: '+880', flag: '🇧🇩', tz: ['Asia/Dhaka'] },
  { code: 'LK', name: 'Sri Lanka', dial: '+94', flag: '🇱🇰', tz: ['Asia/Colombo'] },
  { code: 'NG', name: 'Nigeria', dial: '+234', flag: '🇳🇬', tz: ['Africa/Lagos'] },
  { code: 'ZA', name: 'South Africa', dial: '+27', flag: '🇿🇦', tz: ['Africa/Johannesburg', 'Africa/Cape_Town'] },
  { code: 'KE', name: 'Kenya', dial: '+254', flag: '🇰🇪', tz: ['Africa/Nairobi'] },
  { code: 'EG', name: 'Egypt', dial: '+20', flag: '🇪🇬', tz: ['Africa/Cairo'] },
  { code: 'DE', name: 'Germany', dial: '+49', flag: '🇩🇪', tz: ['Europe/Berlin', 'Europe/Munich', 'Europe/Frankfurt'] },
  { code: 'FR', name: 'France', dial: '+33', flag: '🇫🇷', tz: ['Europe/Paris'] },
  { code: 'IT', name: 'Italy', dial: '+39', flag: '🇮🇹', tz: ['Europe/Rome'] },
  { code: 'ES', name: 'Spain', dial: '+34', flag: '🇪🇸', tz: ['Europe/Madrid', 'Europe/Barcelona'] },
  { code: 'NL', name: 'Netherlands', dial: '+31', flag: '🇳🇱', tz: ['Europe/Amsterdam'] },
  { code: 'SE', name: 'Sweden', dial: '+46', flag: '🇸🇪', tz: ['Europe/Stockholm'] },
  { code: 'NO', name: 'Norway', dial: '+47', flag: '🇳🇴', tz: ['Europe/Oslo'] },
  { code: 'DK', name: 'Denmark', dial: '+45', flag: '🇩🇰', tz: ['Europe/Copenhagen'] },
  { code: 'CH', name: 'Switzerland', dial: '+41', flag: '🇨🇭', tz: ['Europe/Zurich', 'Europe/Bern'] },
  { code: 'JP', name: 'Japan', dial: '+81', flag: '🇯🇵', tz: ['Asia/Tokyo'] },
  { code: 'KR', name: 'South Korea', dial: '+82', flag: '🇰🇷', tz: ['Asia/Seoul'] },
  { code: 'CN', name: 'China', dial: '+86', flag: '🇨🇳', tz: ['Asia/Shanghai', 'Asia/Beijing', 'Asia/Chongqing', 'Asia/Hong_Kong'] },
  { code: 'HK', name: 'Hong Kong', dial: '+852', flag: '🇭🇰', tz: ['Asia/Hong_Kong'] },
  { code: 'TW', name: 'Taiwan', dial: '+886', flag: '🇹🇼', tz: ['Asia/Taipei'] },
  { code: 'TR', name: 'Turkey', dial: '+90', flag: '🇹🇷', tz: ['Europe/Istanbul'] },
  { code: 'RU', name: 'Russia', dial: '+7', flag: '🇷🇺', tz: ['Europe/Moscow', 'Asia/Yekaterinburg', 'Asia/Krasnoyarsk', 'Asia/Vladivostok'] },
  { code: 'BR', name: 'Brazil', dial: '+55', flag: '🇧🇷', tz: ['America/Sao_Paulo', 'America/Rio_de_Janeiro', 'America/Brasilia', 'America/Recife', 'America/Manaus'] },
  { code: 'MX', name: 'Mexico', dial: '+52', flag: '🇲🇽', tz: ['America/Mexico_City', 'America/Tijuana', 'America/Cancun'] },
  { code: 'AR', name: 'Argentina', dial: '+54', flag: '🇦🇷', tz: ['America/Argentina/Buenos_Aires'] },
  { code: 'CO', name: 'Colombia', dial: '+57', flag: '🇨🇴', tz: ['America/Bogota'] },
  { code: 'CL', name: 'Chile', dial: '+56', flag: '🇨🇱', tz: ['America/Santiago'] },
  { code: 'PE', name: 'Peru', dial: '+51', flag: '🇵🇪', tz: ['America/Lima'] },
  { code: 'IE', name: 'Ireland', dial: '+353', flag: '🇮🇪', tz: ['Europe/Dublin'] },
  { code: 'NZ', name: 'New Zealand', dial: '+64', flag: '🇳🇿', tz: ['Pacific/Auckland', 'Pacific/Chatham'] },
  { code: 'IL', name: 'Israel', dial: '+972', flag: '🇮🇱', tz: ['Asia/Jerusalem', 'Asia/Tel_Aviv'] },
  { code: 'QA', name: 'Qatar', dial: '+974', flag: '🇶🇦', tz: ['Asia/Qatar'] },
  { code: 'KW', name: 'Kuwait', dial: '+965', flag: '🇰🇼', tz: ['Asia/Kuwait'] },
  { code: 'OM', name: 'Oman', dial: '+968', flag: '🇴🇲', tz: ['Asia/Muscat'] },
  { code: 'BH', name: 'Bahrain', dial: '+973', flag: '🇧🇭', tz: ['Asia/Bahrain'] },
  { code: 'NP', name: 'Nepal', dial: '+977', flag: '🇳🇵', tz: ['Asia/Kathmandu'] },
  { code: 'AF', name: 'Afghanistan', dial: '+93', flag: '🇦🇫', tz: ['Asia/Kabul'] },
  { code: 'IR', name: 'Iran', dial: '+98', flag: '🇮🇷', tz: ['Asia/Tehran'] },
  { code: 'IQ', name: 'Iraq', dial: '+964', flag: '🇮🇶', tz: ['Asia/Baghdad'] },
  { code: 'JO', name: 'Jordan', dial: '+962', flag: '🇯🇴', tz: ['Asia/Amman'] },
  { code: 'LB', name: 'Lebanon', dial: '+961', flag: '🇱🇧', tz: ['Asia/Beirut'] },
  { code: 'SY', name: 'Syria', dial: '+963', flag: '🇸🇾', tz: ['Asia/Damascus'] },
  { code: 'YE', name: 'Yemen', dial: '+967', flag: '🇾🇪', tz: ['Asia/Aden'] },
  { code: 'MA', name: 'Morocco', dial: '+212', flag: '🇲🇦', tz: ['Africa/Casablanca'] },
  { code: 'DZ', name: 'Algeria', dial: '+213', flag: '🇩🇿', tz: ['Africa/Algiers'] },
  { code: 'TN', name: 'Tunisia', dial: '+216', flag: '🇹🇳', tz: ['Africa/Tunis'] },
  { code: 'LY', name: 'Libya', dial: '+218', flag: '🇱🇾', tz: ['Africa/Tripoli'] },
  { code: 'SD', name: 'Sudan', dial: '+249', flag: '🇸🇩', tz: ['Africa/Khartoum'] },
  { code: 'ET', name: 'Ethiopia', dial: '+251', flag: '🇪🇹', tz: ['Africa/Addis_Ababa'] },
  { code: 'SO', name: 'Somalia', dial: '+252', flag: '🇸🇴', tz: ['Africa/Mogadishu'] },
  { code: 'GH', name: 'Ghana', dial: '+233', flag: '🇬🇭', tz: ['Africa/Accra'] },
  { code: 'TZ', name: 'Tanzania', dial: '+255', flag: '🇹🇿', tz: ['Africa/Dar_es_Salaam'] },
  { code: 'UG', name: 'Uganda', dial: '+256', flag: '🇺🇬', tz: ['Africa/Kampala'] },
  { code: 'AT', name: 'Austria', dial: '+43', flag: '🇦🇹', tz: ['Europe/Vienna'] },
  { code: 'BE', name: 'Belgium', dial: '+32', flag: '🇧🇪', tz: ['Europe/Brussels'] },
  { code: 'BG', name: 'Bulgaria', dial: '+359', flag: '🇧🇬', tz: ['Europe/Sofia'] },
  { code: 'HR', name: 'Croatia', dial: '+385', flag: '🇭🇷', tz: ['Europe/Zagreb'] },
  { code: 'CY', name: 'Cyprus', dial: '+357', flag: '🇨🇾', tz: ['Asia/Nicosia'] },
  { code: 'CZ', name: 'Czech Republic', dial: '+420', flag: '🇨🇿', tz: ['Europe/Prague'] },
  { code: 'EE', name: 'Estonia', dial: '+372', flag: '🇪🇪', tz: ['Europe/Tallinn'] },
  { code: 'FI', name: 'Finland', dial: '+358', flag: '🇫🇮', tz: ['Europe/Helsinki'] },
  { code: 'GR', name: 'Greece', dial: '+30', flag: '🇬🇷', tz: ['Europe/Athens'] },
  { code: 'HU', name: 'Hungary', dial: '+36', flag: '🇭🇺', tz: ['Europe/Budapest'] },
  { code: 'IS', name: 'Iceland', dial: '+354', flag: '🇮🇸', tz: ['Atlantic/Reykjavik'] },
  { code: 'LV', name: 'Latvia', dial: '+371', flag: '🇱🇻', tz: ['Europe/Riga'] },
  { code: 'LT', name: 'Lithuania', dial: '+370', flag: '🇱🇹', tz: ['Europe/Vilnius'] },
  { code: 'LU', name: 'Luxembourg', dial: '+352', flag: '🇱🇺', tz: ['Europe/Luxembourg'] },
  { code: 'MT', name: 'Malta', dial: '+356', flag: '🇲🇹', tz: ['Europe/Malta'] },
  { code: 'MD', name: 'Moldova', dial: '+373', flag: '🇲🇩', tz: ['Europe/Chisinau'] },
  { code: 'ME', name: 'Montenegro', dial: '+382', flag: '🇲🇪', tz: ['Europe/Podgorica'] },
  { code: 'PL', name: 'Poland', dial: '+48', flag: '🇵🇱', tz: ['Europe/Warsaw'] },
  { code: 'PT', name: 'Portugal', dial: '+351', flag: '🇵🇹', tz: ['Europe/Lisbon', 'Atlantic/Azores'] },
  { code: 'RO', name: 'Romania', dial: '+40', flag: '🇷🇴', tz: ['Europe/Bucharest'] },
  { code: 'RS', name: 'Serbia', dial: '+381', flag: '🇷🇸', tz: ['Europe/Belgrade'] },
  { code: 'SK', name: 'Slovakia', dial: '+421', flag: '🇸🇰', tz: ['Europe/Bratislava'] },
  { code: 'SI', name: 'Slovenia', dial: '+386', flag: '🇸🇮', tz: ['Europe/Ljubljana'] },
  { code: 'UA', name: 'Ukraine', dial: '+380', flag: '🇺🇦', tz: ['Europe/Kyiv'] },
  { code: 'VN', name: 'Vietnam', dial: '+84', flag: '🇻🇳', tz: ['Asia/Ho_Chi_Minh', 'Asia/Hanoi'] },
  { code: 'TH', name: 'Thailand', dial: '+66', flag: '🇹🇭', tz: ['Asia/Bangkok'] },
  { code: 'ID', name: 'Indonesia', dial: '+62', flag: '🇮🇩', tz: ['Asia/Jakarta'] },
  { code: 'MM', name: 'Myanmar', dial: '+95', flag: '🇲🇲', tz: ['Asia/Yangon'] },
  { code: 'KH', name: 'Cambodia', dial: '+855', flag: '🇰🇭', tz: ['Asia/Phnom_Penh'] },
  { code: 'LA', name: 'Laos', dial: '+856', flag: '🇱🇦', tz: ['Asia/Vientiane'] },
  { code: 'MN', name: 'Mongolia', dial: '+976', flag: '🇲🇳', tz: ['Asia/Ulaanbaatar'] },
  { code: 'UZ', name: 'Uzbekistan', dial: '+998', flag: '🇺🇿', tz: ['Asia/Tashkent'] },
  { code: 'KZ', name: 'Kazakhstan', dial: '+7', flag: '🇰🇿', tz: ['Asia/Almaty', 'Asia/Astana'] },
  { code: 'AZ', name: 'Azerbaijan', dial: '+994', flag: '🇦🇿', tz: ['Asia/Baku'] },
  { code: 'GE', name: 'Georgia', dial: '+995', flag: '🇬🇪', tz: ['Asia/Tbilisi'] },
  { code: 'AM', name: 'Armenia', dial: '+374', flag: '🇦🇲', tz: ['Asia/Yerevan'] },
  { code: 'BY', name: 'Belarus', dial: '+375', flag: '🇧🇾', tz: ['Europe/Minsk'] },
  { code: 'VE', name: 'Venezuela', dial: '+58', flag: '🇻🇪', tz: ['America/Caracas'] },
  { code: 'EC', name: 'Ecuador', dial: '+593', flag: '🇪🇨', tz: ['America/Guayaquil'] },
  { code: 'BO', name: 'Bolivia', dial: '+591', flag: '🇧🇴', tz: ['America/La_Paz'] },
  { code: 'PY', name: 'Paraguay', dial: '+595', flag: '🇵🇾', tz: ['America/Asuncion'] },
  { code: 'UY', name: 'Uruguay', dial: '+598', flag: '🇺🇾', tz: ['America/Montevideo'] },
  { code: 'CR', name: 'Costa Rica', dial: '+506', flag: '🇨🇷', tz: ['America/Costa_Rica'] },
  { code: 'PA', name: 'Panama', dial: '+507', flag: '🇵🇦', tz: ['America/Panama'] },
  { code: 'GT', name: 'Guatemala', dial: '+502', flag: '🇬🇹', tz: ['America/Guatemala'] },
  { code: 'SV', name: 'El Salvador', dial: '+503', flag: '🇸🇻', tz: ['America/El_Salvador'] },
  { code: 'HN', name: 'Honduras', dial: '+504', flag: '🇭🇳', tz: ['America/Tegucigalpa'] },
  { code: 'NI', name: 'Nicaragua', dial: '+505', flag: '🇳🇮', tz: ['America/Managua'] },
  { code: 'DO', name: 'Dominican Republic', dial: '+1', flag: '🇩🇴', tz: ['America/Santo_Domingo'] },
  { code: 'PR', name: 'Puerto Rico', dial: '+1', flag: '🇵🇷', tz: ['America/Puerto_Rico'] },
  { code: 'JM', name: 'Jamaica', dial: '+1', flag: '🇯🇲', tz: ['America/Jamaica'] },
  { code: 'TT', name: 'Trinidad & Tobago', dial: '+1', flag: '🇹🇹', tz: ['America/Port_of_Spain'] },
  { code: 'BS', name: 'Bahamas', dial: '+1', flag: '🇧🇸', tz: ['America/Nassau'] },
  { code: 'BB', name: 'Barbados', dial: '+1', flag: '🇧🇧', tz: ['America/Barbados'] },
  { code: 'MU', name: 'Mauritius', dial: '+230', flag: '🇲🇺', tz: ['Indian/Mauritius'] },
  { code: 'SC', name: 'Seychelles', dial: '+248', flag: '🇸🇨', tz: ['Indian/Mahe'] },
  { code: 'MV', name: 'Maldives', dial: '+960', flag: '🇲🇻', tz: ['Indian/Maldives'] },
  { code: 'FJ', name: 'Fiji', dial: '+679', flag: '🇫🇯', tz: ['Pacific/Fiji'] },
  { code: 'PG', name: 'Papua New Guinea', dial: '+675', flag: '🇵🇬', tz: ['Pacific/Port_Moresby'] },
];

export function detectCountry(): string {
  if (typeof Intl === 'undefined') return 'US';
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (!tz) return 'US';
    const match = countries.find(c => c.tz.includes(tz) || c.tz.some(t => tz.startsWith(t.replace(/\/.*$/, ''))));
    return match?.code ?? 'US';
  } catch {
    return 'US';
  }
}
